# Generated by Django 4.2.4 on 2023-10-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectsPerClass',
            new_name='ClassWithSubject',
        ),
    ]
