# Generated by Django 4.2.4 on 2023-10-06 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messageforstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageforstudent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageforteacher',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
