# Generated by Django 4.2.4 on 2023-10-08 13:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_messageforstudent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('hw_detail', ckeditor.fields.RichTextField()),
                ('last_day_of_submit', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classwithsubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subjects')),
            ],
            options={
                'verbose_name': 'HomeWork',
                'verbose_name_plural': 'HomeWorks',
            },
        ),
    ]
