# Generated by Django 4.2.4 on 2023-10-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAndSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('upload_note', models.FileField(upload_to='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batch')),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classwithsubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subjects')),
            ],
        ),
    ]
