# Generated by Django 4.2.4 on 2023-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_noteandsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteandsheet',
            name='upload_note',
            field=models.FileField(blank=True, default='coaching.pdf', null=True, upload_to='notes'),
        ),
    ]
