# Generated by Django 4.2.4 on 2023-10-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_noteandsheet_upload_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteandsheet',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='classwithsubject',
            name='s_class',
            field=models.CharField(blank=True, choices=[('প্রথম', 'প্রথম'), ('দ্বিতীয়', 'দ্বিতীয়'), ('তৃতীয়', 'তৃতীয়'), ('চতুর্থ', 'চতুর্থ'), ('পঞ্চম', 'পঞ্চম'), ('ষষ্ঠ', 'ষষ্ঠ'), ('সপ্তম', 'সপ্তম'), ('অস্টম', 'অস্টম'), ('নবম(বিজ্ঞান)', 'নবম(বিজ্ঞান)'), ('নবম(ব্যাবসায় শিক্ষা)', 'নবম(ব্যাবসায় শিক্ষা)'), ('নবম(মানবিক)', 'নবম(মানবিক)'), ('দশম(বিজ্ঞান)', 'দশম(বিজ্ঞান)'), ('দশম(ব্যাবসায় শিক্ষা)', 'দশম(ব্যাবসায় শিক্ষা)'), ('দশম(মানবিক)', 'দশম(মানবিক)'), ('একাদশ (বিজ্ঞান)', 'একাদশ (বিজ্ঞান)'), ('একাদশ (ব্যাবসায় শিক্ষা)', 'একাদশ (ব্যাবসায় শিক্ষা)'), ('একাদশ (মানবিক)', 'একাদশ (মানবিক)'), ('দাদশ (বিজ্ঞান)', 'দাদশ (বিজ্ঞান)'), ('দাদশ (ব্যাবসায় শিক্ষা)', 'দাদশ (ব্যাবসায় শিক্ষা) '), ('দাদশ (মানবিক)', 'দাদশ (মানবিক)')], max_length=50, null=True),
        ),
    ]
