# Generated by Django 4.2.4 on 2023-10-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_quizcategory_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'কইজ উত্তর তৈরি'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'ব্যাচ তৈরি'},
        ),
        migrations.AlterModelOptions(
            name='classwithsubject',
            options={'verbose_name_plural': 'শ্রেণী হিসেবে বিষয় নির্বাচন'},
        ),
        migrations.AlterModelOptions(
            name='createexam',
            options={'verbose_name_plural': 'পরীক্ষা তৈরি করুন'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'ইউজার অ্যাকাউন্ট *VIP* '},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name_plural': 'ইউজার ( অভিভাবক )'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name_plural': 'শিক্ষকদের দেওয়া বাড়িরকাজ'},
        ),
        migrations.AlterModelOptions(
            name='makebatch',
            options={'verbose_name_plural': 'ব্যাচ ও বিষয় ভিত্তিক শিক্ষক'},
        ),
        migrations.AlterModelOptions(
            name='marksofstudent',
            options={'verbose_name_plural': 'শিক্ষার্থীদের মার্কস'},
        ),
        migrations.AlterModelOptions(
            name='messageforstudent',
            options={'verbose_name_plural': 'শিক্ষার্থীদের বার্তা পাঠান'},
        ),
        migrations.AlterModelOptions(
            name='messageforteacher',
            options={'verbose_name_plural': 'শিক্ষকদের বার্তা পাঠান'},
        ),
        migrations.AlterModelOptions(
            name='noteandsheet',
            options={'verbose_name_plural': 'শিক্ষকদের দেওয়া নোট'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'কইজ প্রশ্ন তৈরি'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'কুইজ এর ধরন তৈরি'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name_plural': 'শিফট তৈরি'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'ইউজার ( শিক্ষার্থী )'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'বিষয় যুক্ত করুন'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'ইউজার( শিক্ষক-শিক্ষিকা )'},
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classwithsubject'),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subjects'),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
