# Generated by Django 4.2.4 on 2023-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_studetfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studetfeedback',
            name='rate_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studetfeedback',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
