# Generated by Django 4.2.4 on 2023-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_studetfeedback_rate_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studetfeedback',
            name='already_rated',
            field=models.BooleanField(default=False),
        ),
    ]
