# Generated by Django 4.2.4 on 2023-10-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.batch'),
        ),
    ]
